Titles:
- Skip
- Touhou Hisoutensoku ver1.10 (eng v1.0)
- Touhou Hisoutensoku ver1.10a (eng v1.1a)
SWRSAddr:
    Skip: false
    Touhou Hisoutensoku ver1.10 (eng v1.0): SWRSAddr(437En110).7z
    Touhou Hisoutensoku ver1.10a (eng v1.1a): SWRSAddr(437En110a).7z