Titles:
- 跳过
- 东方非想天则 ～ 追寻特大型人偶之谜 Ver1.10(beta)
- 搶曽旕憐揤懃 乣 挻淲媺僊僯儑儖偺撲傪捛偊 Ver1.10
- Touhou Hisoutensoku ver1.10 (eng v1.0)
- 搶曽旕憐揤懃 乣 挻淲媺僊僯儑儖偺撲傪捛偊 Ver1.10a
- Touhou Hisoutensoku ver1.10a (eng v1.1a)
SWRSAddr:
    Touhou Hisoutensoku ver1.10 (eng v1.0): SWRSAddr(437En110).7z
    Touhou Hisoutensoku ver1.10a (eng v1.1a): SWRSAddr(437En110a).7z
    东方非想天则 ～ 追寻特大型人偶之谜 Ver1.10(beta): SWRSAddr(936Cn110beta).7z
    搶曽旕憐揤懃 乣 挻淲媺僊僯儑儖偺撲傪捛偊 Ver1.10: false
    搶曽旕憐揤懃 乣 挻淲媺僊僯儑儖偺撲傪捛偊 Ver1.10a: SWRSAddr(936Jp110a).7z
    跳过: false