# Things must be done before modify:

# FullSource
# FullOutput
# Fill Account and password
# Value
# TskNetScriptOption

Tsk_MainConfig:
    Encoding: 'mbcs'
    RelativeSource: 'Templates\Tsk_MainConfig.template'
    FullSource: null
    RelativeOutput: 'tsk.ini'
    FullOutput: null
    Config:
    - GameExePath:
        Group: 'GameExePath'
        Mark: '___GamePath'
        Option: 'Hisoutensoku.FileName='
        Value: null
    - TskNetExePath:
        Group: 'TskNetExePath'
        Mark: '___TskNetPath'
        Option: 'Houkokutool.FileName='
        Value: null
    - Comment:
        Group: 'Comment'
        Mark: '___Comment'
        Option: ''
        Value: ''
#
TskNet_LauncherScript:
    Encoding: 'mbcs'
    RelativeSource: 'Templates\TskNet_LauncherScript.template'
    FullSource: null
    RelativeOutput: 'tsk_report-Intl-zhCN-AIO\tsk_report.cmd'
    FullOutput: null
    Config:
    - AskDNS:
        Group: 'Combined'
        Mark: '___nslookup'
        Option: '@'
        Value: 'nslookup tenco.info.americansdyg.com>nul 2>nul'
    - OptionalHint:
        Group: 'Combined'
        Mark: '___optionalHint'
        Option: ''
        Value: ''
    - TskNetScriptName:
        Group: 'Combined'
        Mark: '___subScript'
        Option: '@'
        Value: 'tsk_report-obfs4.cmd'
    - Comment:
        Group: 'Comment'
        Mark: '___Comment'
        Option: ''
        Value: ''
#
TskNet_ProgramScript:
    Encoding: 'mbcs'
    RelativeSource: 'Templates\TskNet_ProgramScript.template'
    FullSource: null
    RelativeOutput: 'tsk_report-Intl-zhCN-AIO\tsk_report-obfs4.cmd'
    FullOutput: null
    Config:
    - EncodingConvert:
        Group: 'Combined'
        Mark: '___EncodingConvert'
        Option: ''
        Value: ''
    - Comment:
        Group: 'Comment'
        Mark: '___Comment'
        Option: ''
        Value: ''
#
TskNet_Account:
    Encoding: 'utf8'
    RelativeSource: 'Templates\TskNet_Account.template'
    FullSource: null
    RelativeOutput: 'tsk_report-Intl-zhCN-AIO\config.yaml'
    FullOutput: null
    Config:
    - TencoAccount:
        Group: 'TencoAccount'
        Mark: '___Account'
        Option: '  name: '
        Value: null
    - TencoPassword:
        Group: 'TencoPassword'
        Mark: '___Password'
        Option: '  password: '
        Value: null
    - Comment:
        Group: 'Comment'
        Mark: '___Comment'
        Option: ''
        Value: ''